### ISSUE TITLE
Pair Data Problem.

### ISSUE THREAD

**Issue by cuiziteng** [onpix/LLNeRF#2]
Hi, dear author, thanks again for your work, I try to run your data on my own codebase now, but I confuse by 2 problems, I think maybe some place I have goes wrong:

(1). There are no paired data for the comparison （still2 scene for example）: 
The normal light images:
![image](https://github.com/onpix/LLNeRF/assets/55396225/f9f4f3f6-a30f-4250-88bd-9be25930e1b2)
The low light images:
![image](https://github.com/onpix/LLNeRF/assets/55396225/d33af678-8238-496e-89c9-5defede34683)

As it shows that DSC01652.png ...  is not in the normal-light part. 

(2). When I run the data on my own codebase (LLFF data format), I found that I could not render NeRF on the normal-light images, the generated images are like the following, I see your code is based on RAW-NeRF, when I run RAW-NeRF data on my code base, everything is OK.

So is this the problem with the camera pose or where did I go wrong? Thank you in advance! 

![WeChat51761edf6b7c60a8b723f6bb14bcd629](https://github.com/onpix/LLNeRF/assets/55396225/bcab4b49-91de-48ff-8d11-39a25f4d1614)

**Comment by onpix** [comment]
Thanks for your attention.
(1) Filenames are not aligned, because normal light images and low-light images are captured using a single camera in turn. Just sort these files by name, and the files of the same index are aligned. 
(2) Do you mean you cannot run your NeRF code on my normal-light data? If so, you may check out if you can run the original multinerf code on this normal-light data, as this repo is based on multinerf.
